name: test-clang-format

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: '.'
        clangFormatVersion: 10
        exclude: './kernel/usb'
        #exclude: './third_party ./external'
        #extensions: 'h,cpp'
        #style: google